// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnyMsg struct {
	Any                  *any.Any `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyMsg) Reset()         { *m = AnyMsg{} }
func (m *AnyMsg) String() string { return proto.CompactTextString(m) }
func (*AnyMsg) ProtoMessage()    {}
func (*AnyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{0}
}

func (m *AnyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMsg.Unmarshal(m, b)
}
func (m *AnyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMsg.Marshal(b, m, deterministic)
}
func (m *AnyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMsg.Merge(m, src)
}
func (m *AnyMsg) XXX_Size() int {
	return xxx_messageInfo_AnyMsg.Size(m)
}
func (m *AnyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMsg proto.InternalMessageInfo

func (m *AnyMsg) GetAny() *any.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

type EchoMsg struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoMsg) Reset()         { *m = EchoMsg{} }
func (m *EchoMsg) String() string { return proto.CompactTextString(m) }
func (*EchoMsg) ProtoMessage()    {}
func (*EchoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{1}
}

func (m *EchoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoMsg.Unmarshal(m, b)
}
func (m *EchoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoMsg.Marshal(b, m, deterministic)
}
func (m *EchoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoMsg.Merge(m, src)
}
func (m *EchoMsg) XXX_Size() int {
	return xxx_messageInfo_EchoMsg.Size(m)
}
func (m *EchoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EchoMsg proto.InternalMessageInfo

func (m *EchoMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AnyMsg)(nil), "pb.AnyMsg")
	proto.RegisterType((*EchoMsg)(nil), "pb.EchoMsg")
}

func init() { proto.RegisterFile("proto/msg.proto", fileDescriptor_85aa4552279d3b4a) }

var fileDescriptor_85aa4552279d3b4a = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0xd7, 0x03, 0xb3, 0x84, 0x98, 0x0a, 0x92, 0xa4, 0x24, 0xd3, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x22, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x69,
	0x25, 0x03, 0x2e, 0x36, 0xc7, 0xbc, 0x4a, 0xdf, 0xe2, 0x74, 0x21, 0x35, 0x2e, 0xe6, 0xc4, 0xbc,
	0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x88, 0x16, 0x3d, 0x98, 0x16, 0x3d,
	0xc7, 0xbc, 0xca, 0x20, 0x90, 0x02, 0x25, 0x65, 0x2e, 0x76, 0xd7, 0xe4, 0x8c, 0x7c, 0x90, 0x16,
	0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xb0, 0x36, 0xce, 0x20, 0x18, 0x37,
	0x89, 0x0d, 0xac, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x70, 0x07, 0xab, 0x61, 0x8f, 0x00,
	0x00, 0x00,
}
